# https://docs.netlify.com/configure-builds/file-based-configuration/

[build.environment]
  NPM_FLAGS = "--version"

[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  publish = "packages/example/dist"

# The following redirect is intended for use with most SPAs 
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
